site_name: NREMC Database Connector Docs

repo_url: https://github.com/kc-nremc/NREMCDatabaseConnector

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - index.md
  - tutorial.md
  - reference.md
  - explanation.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences